*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 22.07.2021 at 17:13:05
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZSWI_V_SWITCH...................................*
FORM GET_DATA_ZSWI_V_SWITCH.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSWI_SWITCH WHERE
(VIM_WHERETAB) .
    CLEAR ZSWI_V_SWITCH .
ZSWI_V_SWITCH-CLIENT =
ZSWI_SWITCH-CLIENT .
ZSWI_V_SWITCH-CODE =
ZSWI_SWITCH-CODE .
ZSWI_V_SWITCH-STATUS =
ZSWI_SWITCH-STATUS .
ZSWI_V_SWITCH-CUSTOM_DETERMINATION_CLASS =
ZSWI_SWITCH-CUSTOM_DETERMINATION_CLASS .
ZSWI_V_SWITCH-CHANGED_AT =
ZSWI_SWITCH-CHANGED_AT .
ZSWI_V_SWITCH-CHANGED_BY =
ZSWI_SWITCH-CHANGED_BY .
<VIM_TOTAL_STRUC> = ZSWI_V_SWITCH.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSWI_V_SWITCH .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSWI_V_SWITCH.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSWI_V_SWITCH-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSWI_SWITCH WHERE
  CODE = ZSWI_V_SWITCH-CODE .
    IF SY-SUBRC = 0.
    DELETE ZSWI_SWITCH .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSWI_SWITCH WHERE
  CODE = ZSWI_V_SWITCH-CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSWI_SWITCH.
    ENDIF.
ZSWI_SWITCH-CLIENT =
ZSWI_V_SWITCH-CLIENT .
ZSWI_SWITCH-CODE =
ZSWI_V_SWITCH-CODE .
ZSWI_SWITCH-STATUS =
ZSWI_V_SWITCH-STATUS .
ZSWI_SWITCH-CUSTOM_DETERMINATION_CLASS =
ZSWI_V_SWITCH-CUSTOM_DETERMINATION_CLASS .
ZSWI_SWITCH-CHANGED_AT =
ZSWI_V_SWITCH-CHANGED_AT .
ZSWI_SWITCH-CHANGED_BY =
ZSWI_V_SWITCH-CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZSWI_SWITCH ##WARN_OK.
    ELSE.
    INSERT ZSWI_SWITCH .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSWI_V_SWITCH-UPD_FLAG,
STATUS_ZSWI_V_SWITCH-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSWI_V_SWITCH.
  SELECT SINGLE * FROM ZSWI_SWITCH WHERE
CODE = ZSWI_V_SWITCH-CODE .
ZSWI_V_SWITCH-CLIENT =
ZSWI_SWITCH-CLIENT .
ZSWI_V_SWITCH-CODE =
ZSWI_SWITCH-CODE .
ZSWI_V_SWITCH-STATUS =
ZSWI_SWITCH-STATUS .
ZSWI_V_SWITCH-CUSTOM_DETERMINATION_CLASS =
ZSWI_SWITCH-CUSTOM_DETERMINATION_CLASS .
ZSWI_V_SWITCH-CHANGED_AT =
ZSWI_SWITCH-CHANGED_AT .
ZSWI_V_SWITCH-CHANGED_BY =
ZSWI_SWITCH-CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSWI_V_SWITCH USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSWI_V_SWITCH-CODE TO
ZSWI_SWITCH-CODE .
MOVE ZSWI_V_SWITCH-CLIENT TO
ZSWI_SWITCH-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSWI_SWITCH'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSWI_SWITCH TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSWI_SWITCH'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
